server:
  port: 8082
  tomcat:
    threads:
      max: 25
    accept-count: 25
    max-connections: 100
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
  sentinel:
    enabled: true

hm:
  db:
    database: hm-cart
  knife4j:
    title: 黑马商城购物车服务接口文档
    desc: "黑马商城购物车服务接口文档"
    package: com.hmall.cart.controller