server:
  port: 8083

feign:
  okhttp:
    enabled: true # 开启OKHttp功能

hm:
  db:
    database: hm-trade
  knife4j:
    title: 黑马商城订单服务接口文档
    desc: "黑马商城订单服务接口文档"
    package: com.hmall.order.controller