server:
  port: 8080
spring:
  application:
    name: hm-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.192.101:8848 # nacos地址
    gateway:
      routes:
        - id: hm-item
          uri: lb://hm-item
          predicates:
            - Path=/items/**,/search/**
        - id: hm-cart
          uri: lb://hm-cart
          predicates:
            - Path=/carts/**,
        - id: hm-order
          uri: lb://hm-order
          predicates:
            - Path=/orders/**,
        - id: hm-pay
          uri: lb://hm-pay
          predicates:
            - Path=/pay-orders/**,
        - id: hm-user
          uri: lb://hm-user
          predicates:
            - Path=/users/**,/addresses/**