server:
  port: 8085
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  db:
    database: hm-user
  knife4j:
    title: 黑马商城用户服务接口文档
    desc: "黑马商城用户服务接口文档"
    package: com.hmall.user.controller